CREATE TABLE `panelsearch_nando_user_activity` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `panel_id` int(11) NOT NULL,
  `panel_version_id` int(11) NOT NULL,
  `gene_symbol` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `gene_id` int(11) NOT NULL,
  `entity_type_id` int(11) NOT NULL,
  `entity_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_from_user` enum('YES','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  `user_id` int(11) NOT NULL,
  `entity_id` bigint(20) DEFAULT NULL,
  `review_id` bigint(20) DEFAULT NULL,
  `original_review_id` bigint(20) DEFAULT NULL,
  `review_comment_id` bigint(20) DEFAULT NULL,
  `former_entity_id` bigint(20) DEFAULT NULL,
  `former_review_id` bigint(20) DEFAULT NULL,
  `former_review_comment_id` bigint(20) DEFAULT NULL,
  `target` enum('review','definition') NOT NULL DEFAULT 'review',
  `action` enum('add','change','delete','classify') NOT NULL DEFAULT 'change',
  `difference` json NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_activity_panel_version_entity_created` (`panel_id`,`entity_name`,`created_at`,`panel_version_id`),
  KEY `idx_activity_group_fields` (`panel_id`,`gene_id`,`entity_type_id`,`entity_name`,`user_id`,`target`,`original_review_id`,`id`),
  KEY `idx_activity_user_id` (`user_id`),
  KEY `idx_activity_multi_filter` (`panel_id`,`gene_id`,`entity_type_id`,`entity_name`,`user_id`,`target`,`original_review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4