CREATE TABLE `user_account` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `google_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `first_name_en` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name_en` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `affiliation_en` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_title_en` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `group_en` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_name_nl` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name_nl` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `affiliation_nl` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_title_nl` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `group_nl` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_type` int(11) NOT NULL,
  `email` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL,
  `uid` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `authentication_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` int(11) NOT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `is_updated` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `google_id` (`google_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
