CREATE TABLE `submission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int(11) NOT NULL,
  `submitter_email` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `submitter_first_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `submitter_last_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `submitter_institution` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `suspected_diseases` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinical_diagnoses` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `final_diagnoses` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phenotypes` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gene_symbols` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ensembl_ids` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entrez_ids` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allelic_states` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `inheritances` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `matching_rule_medical_info` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `matching_rule_phenotype_info` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ignored',
  `matching_rule_genotype_info` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `restrict_matches_to_researchers` tinyint(1) NOT NULL,
  `restrict_matches_to_providers` tinyint(1) NOT NULL,
  `comment` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `submission_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
