CREATE TABLE `panelsearch_nando_entity_review` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `original_review_id` bigint(20) DEFAULT '0',
  `panel_id` int(11) NOT NULL,
  `panel_version_id` int(11) NOT NULL,
  `gene_symbol` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gene_id` int(11) NOT NULL,
  `entity_type_id` int(11) NOT NULL,
  `entity_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_from_user` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  `user_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isValid` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'YES',
  `isDeleted` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  `rating_id` int(11) NOT NULL DEFAULT '100',
  `phenotypes` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `publications` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `mode_of_inheritances` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `position_chromosome` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `position_grch37_start` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `position_grch37_end` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `position_grch38_start` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `position_grch38_end` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `str_repeated_sequence` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `str_normal_repeats` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `str_pathogenic_repeats` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `region_haploinsufficiency_score` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `region_triplosensitivity_score` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `region_required_overlap_percentage` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `region_variant_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `region_verbose_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_new` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  PRIMARY KEY (`id`),
  KEY `entity_type_id` (`entity_type_id`),
  KEY `rating_id` (`rating_id`),
  KEY `panel_version_id` (`panel_version_id`),
  KEY `idx_review_user` (`user_id`,`id`),
  KEY `idx_review_panel_entity` (`panel_id`,`entity_type_id`,`entity_name`,`id`),
  KEY `idx_review_original_id` (`original_review_id`,`id`),
  KEY `idx_review_panel_valid_created` (`panel_id`,`isValid`),
  KEY `idx_review_panel_version` (`panel_id`,`panel_version_id`,`isValid`),
  KEY `idx_review_user_valid` (`user_id`,`isValid`),
  CONSTRAINT `panelsearch_nando_entity_review_ibfk_1` FOREIGN KEY (`entity_type_id`) REFERENCES `panelsearch_nando_entity_type` (`entity_type_id`),
  CONSTRAINT `panelsearch_nando_entity_review_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user_info_psn` (`id`),
  CONSTRAINT `panelsearch_nando_entity_review_ibfk_3` FOREIGN KEY (`rating_id`) REFERENCES `panelsearch_nando_entity_rating` (`rating_id`),
  CONSTRAINT `panelsearch_nando_entity_review_ibfk_4` FOREIGN KEY (`panel_id`) REFERENCES `panelsearch_nando_panel` (`id`),
  CONSTRAINT `panelsearch_nando_entity_review_ibfk_5` FOREIGN KEY (`panel_version_id`) REFERENCES `panelsearch_nando_panel_version` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci