CREATE TABLE `panelsearch_nando_entity` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `panel_id` int(11) NOT NULL,
  `panel_version_id` int(11) NOT NULL,
  `gene_symbol` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gene_id` int(11) NOT NULL,
  `entity_type_id` int(11) NOT NULL,
  `entity_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_from_user` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  `user_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isValid` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'YES',
  `rating_id` int(11) NOT NULL DEFAULT '100',
  `phenotypes` text COLLATE utf8mb4_unicode_ci,
  `publications` text COLLATE utf8mb4_unicode_ci,
  `mode_of_inheritances` text COLLATE utf8mb4_unicode_ci,
  `source` text COLLATE utf8mb4_unicode_ci,
  `comment` text COLLATE utf8mb4_unicode_ci,
  `is_new` enum('YES','NO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `rating_id` (`rating_id`),
  KEY `panel_id` (`panel_id`),
  KEY `panel_version_id` (`panel_version_id`),
  KEY `idx_psn_entity_definition_grouping` (`entity_type_id`,`entity_name`,`panel_id`,`panel_version_id`,`user_id`,`created_at`),
  CONSTRAINT `panelsearch_nando_entity_ibfk_1` FOREIGN KEY (`entity_type_id`) REFERENCES `panelsearch_nando_entity_type` (`entity_type_id`),
  CONSTRAINT `panelsearch_nando_entity_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user_info_psn` (`id`),
  CONSTRAINT `panelsearch_nando_entity_ibfk_3` FOREIGN KEY (`rating_id`) REFERENCES `panelsearch_nando_entity_rating` (`rating_id`),
  CONSTRAINT `panelsearch_nando_entity_ibfk_4` FOREIGN KEY (`panel_id`) REFERENCES `panelsearch_nando_panel` (`id`),
  CONSTRAINT `panelsearch_nando_entity_ibfk_5` FOREIGN KEY (`panel_version_id`) REFERENCES `panelsearch_nando_panel_version` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci